import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Info from '../components/info'
import Name from '../components/name'

export default function Home() {
  return (
    <div className="bg-gray-100 dark:bg-black">
      <Head>
        <title>Tomás Di Maria</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Name/>
      <Info/>
    </div>
  )
}
