import Head from 'next/head';
import Info from '../components/Info';
import Name from '../components/Name';

export default function Home() {
  return (
    <div className='bg-gray-100 dark:bg-black'>
      <Head>
        <title>Tomás Di Maria</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Name />
      <Info />
    </div>
  );
}
